<!doctype html>
<html class="no-js" lang="en">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134931760-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-134931760-1');
  </script>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Handling exceptions in asynchronous code when upgrading to .NET 4.5</title>
  <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  <meta name="description" content="In the post I will try to uncover the pitfalls that arise when handling exceptions in asynchronous code in .NET 4 in the context of .NET 4.5 

 If you...">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="../../css/main.css">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="../../js/vendors/jquery-3.3.1.min.js"><\/script>')</script>

  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <script>
       (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-6974184241884155",
            enable_page_level_ads: true
       });
  </script>
</head>

<body>
  <!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->
  <header class="page-header js-page-header">
    <a class="page-header-logo-container" href="https://weekly-geekly.github.io/index.html"></a>
    <div class="page-header-text">Geekly Articles each Day</div>
  </header>
  <nav class="page-headings-container js-page-headings-container"></nav>
  <div class="tools-bar js-tools-bar">
    <!-- <a href="../../search.html" title="Search">üîé</a> -->
    <a class="js-list-of-headings-button" data-state="closed" href="#" title="Headings">üìú</a>
    <a class="js-go-to-top-button" href="#" title="Go to Top">‚¨ÜÔ∏è</a>
    <a class="js-go-to-bottom-button" href="#" title="Go to Bottom">‚¨áÔ∏è</a>
  </div>
  <a href="http://bit.ly/donateToWeeklyGeekly" class="donate-btn">DONATE</a>
  <section class="page js-page"><h1>Handling exceptions in asynchronous code when upgrading to .NET 4.5</h1><div class="post__text post__text-html js-mediator-article">  In the post I will try to uncover the pitfalls that arise when handling exceptions in asynchronous code in .NET 4 in the context of .NET 4.5 <br><br>  If you are wondering why under some conditions the code from the example below finishes work without an unhandled exception, welcome under cat. <br><a name="habracut"></a><br>  Consider how the code from the example will behave depending on which .NET version is installed on the server: <br><br><pre><code class="cs hljs"><span class="hljs-keyword"><span class="hljs-keyword">class</span></span> <span class="hljs-title"><span class="hljs-title">Program</span></span> { <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">static</span></span></span><span class="hljs-function"> </span><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">void</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">Main</span></span></span><span class="hljs-function">(</span><span class="hljs-params"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-params"><span class="hljs-keyword">string</span></span></span></span><span class="hljs-function"><span class="hljs-params">[] args</span></span></span><span class="hljs-function">)</span></span> { Task.Factory.StartNew(() =&gt; { <span class="hljs-keyword"><span class="hljs-keyword">throw</span></span> <span class="hljs-keyword"><span class="hljs-keyword">new</span></span> Exception(); }); Thread.Sleep(<span class="hljs-number"><span class="hljs-number">1000</span></span>); GC.Collect(); } }</code> </pre> 
      <br>
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <ins class="adsbygoogle"
          style="display:block; text-align:center;"
          data-ad-layout="in-article"
          data-ad-format="fluid"
          data-ad-client="ca-pub-6974184241884155"
          data-ad-slot="8945601208"></ins>
        <script>
          (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
      <br>
      If .NET 4 is installed on the server and .NET 4.5 is not installed, the process will terminate due to an unhandled exception.  The generation of exceptions from tasks that no one expects to complete occurs during garbage collection.  If the example would look like this: <br><br><pre> <code class="cs hljs"><span class="hljs-keyword"><span class="hljs-keyword">class</span></span> <span class="hljs-title"><span class="hljs-title">Program</span></span> { <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">static</span></span></span><span class="hljs-function"> </span><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">void</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">Main</span></span></span><span class="hljs-function">(</span><span class="hljs-params"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-params"><span class="hljs-keyword">string</span></span></span></span><span class="hljs-function"><span class="hljs-params">[] args</span></span></span><span class="hljs-function">)</span></span> { Task.Factory.StartNew(() =&gt; { <span class="hljs-keyword"><span class="hljs-keyword">throw</span></span> <span class="hljs-keyword"><span class="hljs-keyword">new</span></span> Exception(); }); Thread.Sleep(<span class="hljs-number"><span class="hljs-number">1000</span></span>); } }</code> </pre><br><br>  That problem would be hard to notice. <br><br>  To handle such exceptions, the TaskScheduler type has a TaskUnobservedException event.  The event allows you to catch the exception and prevent the completion of the process. <br><br>  If .NET 4.5 is installed on the server, the behavior changes, the process does not end due to an unhandled exception. <br>  If in .NET 4.5 there would be a standard behavior from .NET 4, then in the example below, when garbage collection occurs, after calling the SomeMethod method, the process would end, because  the exception from Async2 () would remain unprocessed: <br><br><pre> <code class="cs hljs"><span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">public</span></span></span><span class="hljs-function"> </span><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">static</span></span></span><span class="hljs-function"> </span><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">async</span></span></span><span class="hljs-function"> Task </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">SomeMethod</span></span></span><span class="hljs-function">(</span><span class="hljs-params"></span><span class="hljs-function"><span class="hljs-params"></span>)</span></span> { <span class="hljs-keyword"><span class="hljs-keyword">try</span></span> { <span class="hljs-keyword"><span class="hljs-keyword">var</span></span> t1 = Async1(); <span class="hljs-keyword"><span class="hljs-keyword">var</span></span> t2 = Async2(); <span class="hljs-keyword"><span class="hljs-keyword">await</span></span> t1; <span class="hljs-keyword"><span class="hljs-keyword">await</span></span> t2; } <span class="hljs-keyword"><span class="hljs-keyword">catch</span></span> { } } <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">public</span></span></span><span class="hljs-function"> </span><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">static</span></span></span><span class="hljs-function"> Task </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">Async1</span></span></span><span class="hljs-function">(</span><span class="hljs-params"></span><span class="hljs-function"><span class="hljs-params"></span>)</span></span> { <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> Task.Factory.StartNew(() =&gt; { <span class="hljs-keyword"><span class="hljs-keyword">throw</span></span> <span class="hljs-keyword"><span class="hljs-keyword">new</span></span> Exception(); }); } <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">public</span></span></span><span class="hljs-function"> </span><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">static</span></span></span><span class="hljs-function"> Task </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">Async2</span></span></span><span class="hljs-function">(</span><span class="hljs-params"></span><span class="hljs-function"><span class="hljs-params"></span>)</span></span> { <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> Task.Factory.StartNew(() =&gt; { <span class="hljs-keyword"><span class="hljs-keyword">throw</span></span> <span class="hljs-keyword"><span class="hljs-keyword">new</span></span> Exception(); }); }</code> </pre><br><br>  To install the default behavior from .NET 4 after installing .NET 4.5, you need to add the <a href="http://msdn.microsoft.com/ru-ru/library/jj160346(v%3Dvs.110).aspx">ThrowUnobservedTaskExceptions</a> key to the application configuration file. <br><br>  In practice, such a change in behavior during the transition from one version of the framework to another is dangerous in that the live may not have .NET 4.5 installed, and the developer works in a system with .NET 4.5.  In this case, the developer may miss such an error.  Therefore, when developing, it is strongly recommended to test the application with the <a href="http://msdn.microsoft.com/ru-ru/library/jj160346(v%3Dvs.110).aspx">ThrowUnobservedTaskExceptions</a> key <a href="http://msdn.microsoft.com/ru-ru/library/jj160346(v%3Dvs.110).aspx">enabled</a> . <br><br>  In .NET 4.5 there is another innovation that can cause a lot of problems - async void methods, which are otherwise handled by the compiler, rather than async Task methods.  <a href="http://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.asyncvoidmethodbuilder(v%3Dvs.110).aspx">AsyncVoidMethodBuilder is</a> used for processing async void methods, and <a href="http://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.asyncvoidmethodbuilder(v%3Dvs.110).aspx">AsyncTaskMethodBuilder</a> for async Task methods.  If errors occur, if there is no synchronization context, an exception will be thrown into the thread pool, which leads to the completion of the process.  Such an exception can be <a href="http://msdn.microsoft.com/en-us/library/system.appdomain.unhandledexception.aspx">caught</a> , but it is impossible to prevent the completion of the process.  async void methods should only be used to handle events from UI elements. <br><br>  An example of a non-obvious use of the async void method, which leads to the completion of the process: <br><br><pre> <code class="cs hljs"><span class="hljs-keyword"><span class="hljs-keyword">new</span></span> List&lt;<span class="hljs-keyword"><span class="hljs-keyword">int</span></span>&gt;().ForEach(<span class="hljs-keyword"><span class="hljs-keyword">async</span></span> i =&gt; { <span class="hljs-keyword"><span class="hljs-keyword">throw</span></span> <span class="hljs-keyword"><span class="hljs-keyword">new</span></span> Exception(); });</code> </pre><br>  If you do not need async void methods, you can add a rule to CI, which, when appearing in As IL using AsyncVoidMethodBuilder, would consider the build unsuccessful. <br><br>  Sources: <br><ol><li>  <a href="http://www.jaylee.org/post/2012/07/08/c-sharp-async-tips-and-tricks-part-2-async-void.aspx">http://www.jaylee.org/post/2012/07/08/c-sharp-async-tips-and-tricks-part-2-async-void.aspx</a> </li><li>  <a href="http://blogs.msdn.com/b/cellfish/archive/2012/10/18/the-tale-of-an-unobservedtaskexception.aspx">http://blogs.msdn.com/b/cellfish/archive/2012/10/18/the-tale-of-an-unobservedtaskexception.aspx</a> </li><li>  <a href="http://blogs.msdn.com/b/pfxteam/archive/2011/09/28/10217876.aspx">http://blogs.msdn.com/b/pfxteam/archive/2011/09/28/10217876.aspx</a> </li></ol></div><p>Source: <a href="https://habr.com/ru/post/231665/">https://habr.com/ru/post/231665/</a></p>
<section class="more-articles-navigation-panel js-more-articles-navigation-panel">
<h4>More articles:</h4>
<nav class="list-of-articles-container js-list-of-articles-container"><ul class="list-of-pages js-list-of-pages">
<li><a href="../231645/index.html">E-commerce platform. Introduction. Part 1</a></li>
<li><a href="../231647/index.html">15 Hyper-V Security Principles</a></li>
<li><a href="../231653/index.html">Linux Mint 17 and DLNA</a></li>
<li><a href="../231655/index.html">September 17th, we invite you to the conference Fujitsu World Tour 2014</a></li>
<li><a href="../231657/index.html">We write a simple interpreter in C ++ using TDD, part 1</a></li>
<li><a href="../231667/index.html">12 rules of good taste in business communication in English</a></li>
<li><a href="../231671/index.html">Gentleman's kit tester version ZeptoLab</a></li>
<li><a href="../231679/index.html">Literacy is not in decline</a></li>
<li><a href="../231685/index.html">PHPCI updated to version 1.3</a></li>
<li><a href="../231687/index.html">Improving site conversion: 5 ways to avoid creating bad microcopy. Part 1</a></li>
</ul></nav>
</section><br />
<a href="../../allArticles.html"><strong>All Articles</strong></a>
<script src="../../js/main.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
          try {
              w.yaCounter52496797 = new Ya.Metrika({
                  id:52496797,
                  clickmap:true,
                  trackLinks:true,
                  accurateTrackBounce:true,
                  webvisor:true
              });
          } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = "https://mc.yandex.ru/metrika/watch.js";

      if (w.opera == "[object Opera]") {
          d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/52496797" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

<!-- Google Analytics -->
  <script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-134931760-1', 'auto'); ga('send', 'pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async defer></script>

</section>

  <footer class="page-footer">
    <div class="page-footer-legal-info-container page-footer-element">
      <p>
        Weekly-Geekly | <span class="page-footer-legal-info-year js-page-footer-legal-info-year">2019</span>
      </p>
    </div>
    <div class="page-footer-counters-container page-footer-element">
      <a class="page-footer-counter-clustrmap" href='#'  title='Visit tracker'><img src='https://clustrmaps.com/map_v2.png?cl=698e5a&w=271&t=t&d=6iCFw7uJz0zcOaoxz5k5PcLCJUzv2WG8G5V8M3U6Rc4&co=3a3a3a&ct=ffffff'/></a>
    </div>
  </footer>
</body>

</html>