<!doctype html>
<html class="no-js" lang="en">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134931760-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-134931760-1');
  </script>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>How to use exceptions</title>
  <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  <meta name="description" content="The use of exceptions to control program flow (flow control) is a long - standing topic . I would like to summarize this topic and give examples of th...">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="../../css/main.css">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="../../js/vendors/jquery-3.3.1.min.js"><\/script>')</script>

  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <script>
       (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-6974184241884155",
            enable_page_level_ads: true
       });
  </script>
</head>

<body>
  <!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->
  <header class="page-header js-page-header">
    <a class="page-header-logo-container" href="https://weekly-geekly.github.io/index.html"></a>
    <div class="page-header-text">Geekly Articles each Day</div>
  </header>
  <nav class="page-headings-container js-page-headings-container"></nav>
  <div class="tools-bar js-tools-bar">
    <!-- <a href="../../search.html" title="Search">üîé</a> -->
    <a class="js-list-of-headings-button" data-state="closed" href="#" title="Headings">üìú</a>
    <a class="js-go-to-top-button" href="#" title="Go to Top">‚¨ÜÔ∏è</a>
    <a class="js-go-to-bottom-button" href="#" title="Go to Bottom">‚¨áÔ∏è</a>
  </div>
  <a href="http://bit.ly/donateToWeeklyGeekly" class="donate-btn">DONATE</a>
  <section class="page js-page"><h1>How to use exceptions</h1><div class="post__text post__text-html js-mediator-article">  The use of exceptions to control program flow (flow control) is a <a href="http://c2.com/cgi/wiki%3FDontUseExceptionsForFlowControl">long</a> - <a href="http://c2.com/cgi/wiki%3FDontUseExceptionsForFlowControl">standing</a> <a href="http://stackoverflow.com/questions/729379/why-not-use-exceptions-as-regular-flow-of-control">topic</a> .  I would like to summarize this topic and give examples of the correct and incorrect use of exceptions. <br><a name="habracut"></a><br><h2>  Exceptions instead of if-s: why not? </h2><br>  In most cases, we read the code more often than we write.  Most programming practices are aimed at simplifying the understanding of code: the simpler the code, the less bugs it contains and the simpler its support. <br><br>  Using exceptions to control the progress of a program masks the programmer‚Äôs intentions, so this is considered bad practice. <br><br><pre><code class="hljs pgsql"><span class="hljs-built_in"><span class="hljs-built_in">public</span></span> <span class="hljs-type"><span class="hljs-type">void</span></span> ProcessItem(Item item) { <span class="hljs-keyword"><span class="hljs-keyword">if</span></span> (_knownItems.Contains(item)) { // <span class="hljs-keyword"><span class="hljs-keyword">Do</span></span> something throw <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> SuccessException(); } <span class="hljs-keyword"><span class="hljs-keyword">else</span></span> { throw <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> FailureException(); } }</code> </pre> <br>  The ProcessItem method complicates code understanding, since  it is impossible to say what the results of its execution are possible just by looking at its signature.  Such code violates the principle of <a href="http://c2.com/cgi/wiki%3FPrincipleOfLeastAstonishment">least surprise</a> , since  throws an exception even in case of a positive outcome. 
      <br>
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <ins class="adsbygoogle"
          style="display:block; text-align:center;"
          data-ad-layout="in-article"
          data-ad-format="fluid"
          data-ad-client="ca-pub-6974184241884155"
          data-ad-slot="8945601208"></ins>
        <script>
          (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
      <br>
      In this particular case, the solution is obvious - it is necessary to replace the throwing of an exception by returning a boolean value.  Let's look at more complex examples. <br><br><h2>  Exceptions for validating incoming data </h2><br>  Perhaps the most common practice in the context of exceptions is to use them in case of receiving invalid input data. <br><br><pre> <code class="hljs pgsql"><span class="hljs-built_in"><span class="hljs-built_in">public</span></span> <span class="hljs-keyword"><span class="hljs-keyword">class</span></span> EmployeeController : Controller { [HttpPost] <span class="hljs-built_in"><span class="hljs-built_in">public</span></span> ActionResult CreateEmployee(string <span class="hljs-type"><span class="hljs-type">name</span></span>, <span class="hljs-type"><span class="hljs-type">int</span></span> departmentId) { try { ValidateName(<span class="hljs-type"><span class="hljs-type">name</span></span>); Department department = GetDepartment(departmentId); // Rest <span class="hljs-keyword"><span class="hljs-keyword">of</span></span> the <span class="hljs-keyword"><span class="hljs-keyword">method</span></span> } catch (ValidationException ex) { // <span class="hljs-keyword"><span class="hljs-keyword">Return</span></span> <span class="hljs-keyword"><span class="hljs-keyword">view</span></span> <span class="hljs-keyword"><span class="hljs-keyword">with</span></span> error } } private <span class="hljs-type"><span class="hljs-type">void</span></span> ValidateName(string <span class="hljs-type"><span class="hljs-type">name</span></span>) { <span class="hljs-keyword"><span class="hljs-keyword">if</span></span> (string.IsNullOrWhiteSpace(<span class="hljs-type"><span class="hljs-type">name</span></span>)) throw <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> ValidationException(‚Äú<span class="hljs-type"><span class="hljs-type">Name</span></span> cannot be empty‚Äù); <span class="hljs-keyword"><span class="hljs-keyword">if</span></span> (<span class="hljs-type"><span class="hljs-type">name</span></span>.Length &gt; <span class="hljs-number"><span class="hljs-number">100</span></span>) throw <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> ValidationException(‚Äú<span class="hljs-type"><span class="hljs-type">Name</span></span> length cannot exceed <span class="hljs-number"><span class="hljs-number">100</span></span> characters‚Äù); } private Department GetDepartment(<span class="hljs-type"><span class="hljs-type">int</span></span> departmentId) { <span class="hljs-keyword"><span class="hljs-keyword">using</span></span> (EmployeeContext context = <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> EmployeeContext()) { Department department = context.Departments .SingleOrDefault(x =&gt; x.Id == departmentId); <span class="hljs-keyword"><span class="hljs-keyword">if</span></span> (department == <span class="hljs-keyword"><span class="hljs-keyword">null</span></span>) throw <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> ValidationException(‚ÄúDepartment <span class="hljs-keyword"><span class="hljs-keyword">with</span></span> such Id does <span class="hljs-keyword"><span class="hljs-keyword">not</span></span> exist‚Äù); <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> department; } } }</code> </pre><br>  Obviously, this approach has some advantages: it allows us to quickly ‚Äúreturn‚Äù from any method directly to the catch block of the CreateEmployee method. <br><br>  Now let's look at the following example: <br><br><pre> <code class="hljs pgsql"><span class="hljs-built_in"><span class="hljs-built_in">public</span></span> static Employee FindAndProcessEmployee(IList&lt;Employee&gt; employees, string taskName) { Employee <span class="hljs-built_in"><span class="hljs-built_in">found</span></span> = <span class="hljs-keyword"><span class="hljs-keyword">null</span></span>; <span class="hljs-keyword"><span class="hljs-keyword">foreach</span></span> (Employee employee <span class="hljs-keyword"><span class="hljs-keyword">in</span></span> employees) { <span class="hljs-keyword"><span class="hljs-keyword">foreach</span></span> (Task task <span class="hljs-keyword"><span class="hljs-keyword">in</span></span> employee.Tasks) { <span class="hljs-keyword"><span class="hljs-keyword">if</span></span> (task.Name == taskName) { <span class="hljs-built_in"><span class="hljs-built_in">found</span></span> = employee; goto M1; } } } // <span class="hljs-keyword"><span class="hljs-keyword">Some</span></span> code M1: <span class="hljs-built_in"><span class="hljs-built_in">found</span></span>.IsProcessed = <span class="hljs-keyword"><span class="hljs-keyword">true</span></span>; <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> <span class="hljs-built_in"><span class="hljs-built_in">found</span></span>; }</code> </pre><br>  What do these two samples have in common?  Both of them allow you to interrupt the current thread of execution and quickly jump to a certain point in the code.  The only problem with this code is that it significantly degrades readability.  Both approaches make it difficult to understand the code, which is why the use of exceptions to control the flow of a program is often equalized with the use of goto. <br><br>  When using exceptions it is difficult to understand exactly where they are caught.  You can wrap a code that throws an exception into a try / catch block in the same method, or you can put a try / catch block several levels higher.  You can never know for sure whether this is done intentionally or not: <br><br><pre> <code class="hljs cs"><span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">public</span></span></span><span class="hljs-function"> Employee </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">CreateEmployee</span></span></span><span class="hljs-function">(</span><span class="hljs-params"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-params"><span class="hljs-keyword">string</span></span></span></span><span class="hljs-function"><span class="hljs-params"> name, </span></span><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-params"><span class="hljs-keyword">int</span></span></span></span><span class="hljs-function"><span class="hljs-params"> departmentId</span></span></span><span class="hljs-function">)</span></span> { <span class="hljs-comment"><span class="hljs-comment">//          try/catch ? ValidateName(name); // Rest of the method }</span></span></code> </pre><br>  The only way to find out is to analyze the entire stack.  Exceptions used for validation make the code much less readable, because  they do not clearly show the intentions of the developer.  <b>It is impossible to simply look at such a code and say what might go wrong and how to respond to it</b> . <br><br>  Is there a better way?  Of course: <br><br><pre> <code class="hljs pgsql">[HttpPost] <span class="hljs-built_in"><span class="hljs-built_in">public</span></span> ActionResult CreateEmployee(string <span class="hljs-type"><span class="hljs-type">name</span></span>, <span class="hljs-type"><span class="hljs-type">int</span></span> departmentId) { <span class="hljs-keyword"><span class="hljs-keyword">if</span></span> (!IsNameValid(<span class="hljs-type"><span class="hljs-type">name</span></span>)) { // <span class="hljs-keyword"><span class="hljs-keyword">Return</span></span> <span class="hljs-keyword"><span class="hljs-keyword">view</span></span> <span class="hljs-keyword"><span class="hljs-keyword">with</span></span> error } <span class="hljs-keyword"><span class="hljs-keyword">if</span></span> (!IsDepartmentValid(departmentId)) { // <span class="hljs-keyword"><span class="hljs-keyword">Return</span></span> <span class="hljs-keyword"><span class="hljs-keyword">view</span></span> <span class="hljs-keyword"><span class="hljs-keyword">with</span></span> another error } Employee employee = <span class="hljs-built_in"><span class="hljs-built_in">new</span></span> Employee(<span class="hljs-type"><span class="hljs-type">name</span></span>, departmentId); // Rest <span class="hljs-keyword"><span class="hljs-keyword">of</span></span> the <span class="hljs-keyword"><span class="hljs-keyword">method</span></span> }</code> </pre><br>  Specifying all checks explicitly makes your intentions much more understandable.  This version of the method is simple and obvious. <br><br><h2>  Exceptions for exceptions </h2><br>  So when to use exceptions?  The main goal of exceptions is a surprise!  - mark the exception in the application.  An exceptional situation is a situation in which you do not know what to do and the best way out for you is to stop performing the current operation (perhaps with preliminary logging of the details of the error). <br><br>  Examples of exceptional situations can be problems with connecting to the database, the lack of necessary configuration files, etc.  Validation errors <a href="http://enterprisecraftsmanship.com/2015/02/14/code-contracts-vs-input-validation/">are not exceptional</a> , because  The method that checks incoming data expects by definition that it may be incorrect. <br><br>  Another example of the correct use of exceptions is the code contract validation.  You, as the author of the class, expect customers of this class to honor his contracts.  The situation in which the contract method is not respected is exceptional and deserves an exception being thrown. <br><br><h2>  How to handle exceptions thrown by other libraries? </h2><br>  Whether the situation is exceptional depends on the context.  The developer of a third-party library may not know how to deal with problems connecting to the database, since  he does not know in what context his library will be used. <br><br>  In the case of a similar problem, the library developer is not able to do anything with it, so throwing an exception would be an appropriate solution.  You can take the Entity Framework or NHibernate as an example: they expect that the database is always available and if this is not the case, throw an exception. <br><br>  On the other hand, a developer using the library can <b>expect</b> the database to go offline from time to time and develop its application with this fact in mind.  In case of failure of the database, the client application may try to repeat the same operation or display a message to the user with an offer to repeat the operation later. <br><br>  Thus, the situation may be exceptional from the point of view of the underlying code and expected from the point of view of the client code.  How in this case to work with the exceptions thrown by such library? <br><br>  <b>Such exceptions should be caught as close as possible to the code that throws them out</b> .  If this is not the case, your code will have the same drawbacks as the sample code with goto: it will not be possible to understand where this exception is processed without analyzing the entire call stack. <br><br><pre> <code class="hljs cs"><span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">public</span></span></span><span class="hljs-function"> </span><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">void</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">CreateCustomer</span></span></span><span class="hljs-function">(</span><span class="hljs-params"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-params"><span class="hljs-keyword">string</span></span></span></span><span class="hljs-function"><span class="hljs-params"> name</span></span></span><span class="hljs-function">)</span></span> { Customer customer = <span class="hljs-keyword"><span class="hljs-keyword">new</span></span> Customer(name); <span class="hljs-keyword"><span class="hljs-keyword">bool</span></span> result = SaveCustomer(customer); <span class="hljs-keyword"><span class="hljs-keyword">if</span></span> (!result) { MessageBox.Show(‚ÄúError connecting to the database. Please <span class="hljs-keyword"><span class="hljs-keyword">try</span></span> again later.‚Äù); } } <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">private</span></span></span><span class="hljs-function"> </span><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">bool</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">SaveCustomer</span></span></span><span class="hljs-function">(</span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">Customer customer</span></span></span><span class="hljs-function">)</span></span> { <span class="hljs-keyword"><span class="hljs-keyword">try</span></span> { <span class="hljs-keyword"><span class="hljs-keyword">using</span></span> (MyContext context = <span class="hljs-keyword"><span class="hljs-keyword">new</span></span> MyContext()) { context.Customers.Add(customer); context.SaveChanges(); } <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> <span class="hljs-literal"><span class="hljs-literal">true</span></span>; } <span class="hljs-keyword"><span class="hljs-keyword">catch</span></span> (DbUpdateException ex) { <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> <span class="hljs-literal"><span class="hljs-literal">false</span></span>; } }</code> </pre><br>  As can be seen in the example above, the SaveCustomer method expects problems with the database and intentionally catches all errors related to this.  It returns a boolean flag, which is then processed by the code above in the stack. <br><br>  The SaveCustomer method has a clear signature that tells us that there may be problems in the client saving process, that these problems are expected and that you should check the return value to make sure everything is in order. <br><br>  It is worth noting the well-known practice applicable in this case: no need to wrap such code in a generic handler.  The generic handler claims that <b>any</b> exceptions are expected, which is essentially not true. <br><br>  If you really expect any exceptions, you do so for a very limited number of them, for which you know for sure that you can handle them.  Placing a generic handler causes you to swallow the exceptions that you did not expect, putting the application in a non-consistent state. <br><br>  The only situation in which generic handlers are applicable is to place them at the highest level in the application stack to catch all exceptions not caught by the code below in order to log them.  Such exceptions should not be attempted to be processed; all that can be done is to close the application (in the case of a stateful application) or stop the current operation (in the case of a stateless application). <br><br><h2>  Exceptions and fail-fast principle </h2><br><br>  How often do you come across code like this? <br><br><pre> <code class="hljs cs"><span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">public</span></span></span><span class="hljs-function"> </span><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">bool</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">CreateCustomer</span></span></span><span class="hljs-function">(</span><span class="hljs-params"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-params"><span class="hljs-keyword">int</span></span></span></span><span class="hljs-function"><span class="hljs-params"> managerId, </span></span><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-params"><span class="hljs-keyword">string</span></span></span></span><span class="hljs-function"><span class="hljs-params"> addressString, </span></span><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-params"><span class="hljs-keyword">string</span></span></span></span><span class="hljs-function"><span class="hljs-params"> departmentName</span></span></span><span class="hljs-function">)</span></span> { <span class="hljs-keyword"><span class="hljs-keyword">try</span></span> { Manager manager = GetManager(managerId); Address address = CreateAddress(addressString); Department department = GetDepartment(departmentName); CreateCustomerCore(manager, address, department); <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> <span class="hljs-literal"><span class="hljs-literal">true</span></span>; } <span class="hljs-keyword"><span class="hljs-keyword">catch</span></span> (Exception ex) { _logger.Log(ex); <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> <span class="hljs-literal"><span class="hljs-literal">false</span></span>; } }</code> </pre><br>  This is an example of incorrect use of a generic exception handler.  The code above implies that all exceptions coming from the body of the method are a sign of an error in the process of creating a custom tester.  What is the problem with this code? <br><br>  In addition to the similarity with the ‚Äúgoto‚Äù semantics discussed above, the problem is that an exception, a block coming to a catch may not be an exception we know.  The exception can be either ArgumentException, which we expect, or ContractViolationException.  In the latter case, we hide the bug by pretending that we know how to handle such an exception. <br><br>  Then, a similar approach is used by developers who want to protect their application from unexpected drops.  In fact, this approach only masks the problems, making it harder to catch them. <br><br>  The best way to work with unexpected exceptions is to stop the current operation completely and prevent the non-consistent state from spreading across the application. <br><br><h2>  Conclusion </h2><br><ul><li>  Throw an exception if and only if you need to declare an exceptional situation in the code. </li><li>  Use return values ‚Äã‚Äãwhen validating incoming data. </li><li>  If you know how to handle exceptions thrown by the library, do it as close as possible to the code that throws them. </li><li>  If you are dealing with an unexpected exception, stop the current operation completely.  Do not pretend to know how to deal with such exceptions. </li></ul><br>  Link to original article: <a href="http://enterprisecraftsmanship.com/2015/02/26/exceptions-for-flow-control-in-c/">Exceptions for flow control in C #</a> </div><p>Source: <a href="https://habr.com/ru/post/263685/">https://habr.com/ru/post/263685/</a></p>
<section class="more-articles-navigation-panel js-more-articles-navigation-panel">
<h4>More articles:</h4>
<nav class="list-of-articles-container js-list-of-articles-container"><ul class="list-of-pages js-list-of-pages">
<li><a href="../263671/index.html">Compare .NET calendars. Experience first acquaintance</a></li>
<li><a href="../263673/index.html">ZeroRPC is a lightweight, reliable library for distributed communication between servers.</a></li>
<li><a href="../263675/index.html">Oracle Form Study with Java Development API (JDAPI)</a></li>
<li><a href="../263677/index.html">Unit tests in Cach√© are just</a></li>
<li><a href="../263681/index.html">And we decided to make friends with Baresip and Nodejs</a></li>
<li><a href="../263687/index.html">Magic of tensor algebra: Part 14 - Non-standard introduction to the dynamics of a rigid body</a></li>
<li><a href="../263689/index.html">Joker 2015: News July 16-27, 2015 - new speakers and reports</a></li>
<li><a href="../263691/index.html">vCloud Director for the smallest (part 5): VPN setup</a></li>
<li><a href="../263693/index.html">Why do we need business intelligence systems</a></li>
<li><a href="../263695/index.html">The ideal way to implement a static code analyzer</a></li>
</ul></nav>
</section><br />
<a href="../../allArticles.html"><strong>All Articles</strong></a>
<script src="../../js/main.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
          try {
              w.yaCounter52496797 = new Ya.Metrika({
                  id:52496797,
                  clickmap:true,
                  trackLinks:true,
                  accurateTrackBounce:true,
                  webvisor:true
              });
          } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = "https://mc.yandex.ru/metrika/watch.js";

      if (w.opera == "[object Opera]") {
          d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/52496797" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

<!-- Google Analytics -->
  <script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-134931760-1', 'auto'); ga('send', 'pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async defer></script>

</section>

  <footer class="page-footer">
    <div class="page-footer-legal-info-container page-footer-element">
      <p>
        Weekly-Geekly | <span class="page-footer-legal-info-year js-page-footer-legal-info-year">2019</span>
      </p>
    </div>
    <div class="page-footer-counters-container page-footer-element">
      <a class="page-footer-counter-clustrmap" href='#'  title='Visit tracker'><img src='https://clustrmaps.com/map_v2.png?cl=698e5a&w=271&t=t&d=6iCFw7uJz0zcOaoxz5k5PcLCJUzv2WG8G5V8M3U6Rc4&co=3a3a3a&ct=ffffff'/></a>
    </div>
  </footer>
</body>

</html>