<!doctype html>
<html class="no-js" lang="en">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134931760-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-134931760-1');
  </script>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Try / Catch / Finally</title>
  <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  <meta name="description" content="When you use Try / Catch / Finally , the command to be executed is placed in a Try block. If an error occurs during the execution of the command, it w...">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="../../css/main.css">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="../../js/vendors/jquery-3.3.1.min.js"><\/script>')</script>

  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <script>
       (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-6974184241884155",
            enable_page_level_ads: true
       });
  </script>
</head>

<body>
  <!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->
  <header class="page-header js-page-header">
    <a class="page-header-logo-container" href="https://weekly-geekly.github.io/index.html"></a>
    <div class="page-header-text">Geekly Articles each Day</div>
  </header>
  <nav class="page-headings-container js-page-headings-container"></nav>
  <div class="tools-bar js-tools-bar">
    <!-- <a href="../../search.html" title="Search">üîé</a> -->
    <a class="js-list-of-headings-button" data-state="closed" href="#" title="Headings">üìú</a>
    <a class="js-go-to-top-button" href="#" title="Go to Top">‚¨ÜÔ∏è</a>
    <a class="js-go-to-bottom-button" href="#" title="Go to Bottom">‚¨áÔ∏è</a>
  </div>
  <a href="http://bit.ly/donateToWeeklyGeekly" class="donate-btn">DONATE</a>
  <section class="page js-page"><h1>Try / Catch / Finally</h1><div class="post__text post__text-html js-mediator-article">  When you use <b>Try / Catch / Finally</b> , the command to be executed is placed in a <b>Try</b> block.  If an error occurs during the execution of the command, it will be written to the <b>$ Error</b> variable, and the script will go to the <b>Catch</b> block. <br><a name="habracut"></a><br>  The <i>TestTryCatchFinally.ps1</i> script uses a <b>Try</b> command in an attempt to create an object.  The creation object is in the <b>$ ob1</b> variable.  The <b>New-Object cmdlet</b> creates an object.  After creating an object and placing it in the <b>$ a</b> variable, you can view the members of the object using the <b>Get-Member</b> cmdlet.  The following code illustrates this: <br><br><pre><code class="hljs perl">Try { <span class="hljs-string"><span class="hljs-string">"Attempting to create new object $ob1"</span></span> $a = new-object $ob1 <span class="hljs-string"><span class="hljs-string">"Members of the $ob1"</span></span> <span class="hljs-string"><span class="hljs-string">"New object $ob1 created"</span></span> $a | Get-Member }</code> </pre> <br>  Use the <b>Catch</b> block to catch the error that occurred in the <b>Try</b> block.  You can specify the type of error to capture, as well as the action that would occur when an error occurred.  In the <i>TestTryCatchFinally.ps1</i> script <i>,</i> I watch for errors like <a href="http://msdn.microsoft.com/en-us/library/system.exception.aspx">System.Exception</a> .  The <b>System.Exeption</b> .Net Framework class is the base class on which all other exceptions depend.  This means that <b>System.Exeption</b> is a generic generic class; in essence, you can get all the predefined exceptions, both general and system-wide.  When catching an error, you can specify which code you would like to execute.  In this example, I display a simple line that indicates that the script caught a system exception.  The <b>Catch</b> block is shown below: <br><br><pre> <code class="hljs pgsql">Catch { [<span class="hljs-keyword"><span class="hljs-keyword">system</span></span>.<span class="hljs-keyword"><span class="hljs-keyword">exception</span></span>] "caught a system exception" }</code> </pre><br>  The <b>Finally</b> block of the <b>Try / Catch /</b> <b>Finally</b> sequence is always executed, regardless of whether an error occurred or not.  This means that some things to complete that you want to do, for example, to explicitly release a COM object, should be placed in the <b>Finally</b> block.  In the <i>TestTryCatchFinally.ps1</i> script, the <i>finally</i> block illustrates the status bar that the script has completed.  This is shown below: 
      <br>
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <ins class="adsbygoogle"
          style="display:block; text-align:center;"
          data-ad-layout="in-article"
          data-ad-format="fluid"
          data-ad-client="ca-pub-6974184241884155"
          data-ad-slot="8945601208"></ins>
        <script>
          (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
      <br>
    <pre> <code class="hljs php"><span class="hljs-keyword"><span class="hljs-keyword">Finally</span></span> { <span class="hljs-string"><span class="hljs-string">"end of script"</span></span> }</code> </pre><br>  <i>Entire TestTryCatchFinally.ps1</i> script: <br><br>  <b>TestTryCatchFinally.ps1</b> <br><pre> <code class="hljs sql">$ob1 = "kenobie" "<span class="hljs-keyword"><span class="hljs-keyword">Begin</span></span> <span class="hljs-keyword"><span class="hljs-keyword">test</span></span><span class="hljs-string"><span class="hljs-string">" Try { "</span></span>Attempting <span class="hljs-keyword"><span class="hljs-keyword">to</span></span> <span class="hljs-keyword"><span class="hljs-keyword">create</span></span> <span class="hljs-keyword"><span class="hljs-keyword">new</span></span> <span class="hljs-keyword"><span class="hljs-keyword">object</span></span> $ob1<span class="hljs-string"><span class="hljs-string">" $a = new-object $ob1 "</span></span>Members <span class="hljs-keyword"><span class="hljs-keyword">of</span></span> the $ob1<span class="hljs-string"><span class="hljs-string">" "</span></span><span class="hljs-keyword"><span class="hljs-keyword">New</span></span> <span class="hljs-keyword"><span class="hljs-keyword">object</span></span> $ob1 created<span class="hljs-string"><span class="hljs-string">" $a | Get-Member } Catch [system.exception] { "</span></span>caught a <span class="hljs-keyword"><span class="hljs-keyword">system</span></span> <span class="hljs-keyword"><span class="hljs-keyword">exception</span></span><span class="hljs-string"><span class="hljs-string">" } Finally { "</span></span><span class="hljs-keyword"><span class="hljs-keyword">end</span></span> <span class="hljs-keyword"><span class="hljs-keyword">of</span></span> script<span class="hljs-string"><span class="hljs-string">" }</span></span></code> </pre><br>  During the execution of the <i>TestTryCatchFinally.ps1</i> script <i>,</i> when the <b>$ ob1</b> variable is assigned the value ‚Äúkenobie‚Äù, an error occurs because there is not a single object named ‚Äúkenobie‚Äù that could be created using the <b>New-Object cmdlet</b> .  The following picture shows the output of the script. <br><br><img src="https://habrastorage.org/files/fca/3f7/c41/fca3f7c417ec49009f68ca2d593a33f9.jpg"><br><br>  As you can see from the previous picture, the string ‚ÄúBegin Test‚Äù is output because it is outside the <b>Try / Catch / Finally</b> loop.  Inside the <b>Try</b> block, the string ‚ÄúAttempting to create new object kenobie‚Äù is output because it is executed before the <b>New-Object</b> command.  This demonstrates that the <b>Try</b> block is always trying to execute the code inside it.  Members of the "kenobie" object are not displayed, just as the string "new object kenobie created" is not displayed.  This indicates that after an error occurs, the script proceeds to the next block.  In the <b>Catch</b> block, an error of type <b>System.Exeption occurs</b> and the string ‚Äúcaught a system exception‚Äù is output.  Next, the script goes to the <b>Finally</b> block and displays the string "end of script". <br><br>  If in the script the variable <b>$ ob1</b> is assigned the value ‚Äúsystem.object‚Äù (which is the correct value), the <b>Try</b> block will succeed completely.  This is seen in the following figure, the members of the object are inferred, and the string indicating that the object is successfully created is also output.  The <b>Catch</b> block does not work, and the string "end of script" from the <b>Finally</b> block is output. <br><br><img src="https://habrastorage.org/files/8d7/9fd/126/8d79fd126063411885af676f5785d1a5.jpg"><br><br>  You can use multiple <b>Catch</b> blocks in a <b>Try / Catch / Finally</b> block.  It should be borne in mind that when an exception occurs Windows Powershell leaves the <b>Try</b> block and searches for the <b>Catch</b> block.  The first <b>Catch</b> block will be used that satisfies the exception condition.  Therefore, it is necessary to use the most specific exceptions first, moving on to more general ones. <br>  This is seen in <i>TestTryMultipleCatchFinally.ps1</i> . <br><br>  <b>TestTryMultipleCatchFinally.ps1</b> <br><pre> <code class="hljs sql">$ob1 = "foo" "<span class="hljs-keyword"><span class="hljs-keyword">Begin</span></span> <span class="hljs-keyword"><span class="hljs-keyword">test</span></span><span class="hljs-string"><span class="hljs-string">" $ErrorActionPreference = "</span></span><span class="hljs-keyword"><span class="hljs-keyword">stop</span></span><span class="hljs-string"><span class="hljs-string">" Try { Get-Content foo "</span></span>Attempting <span class="hljs-keyword"><span class="hljs-keyword">to</span></span> <span class="hljs-keyword"><span class="hljs-keyword">create</span></span> <span class="hljs-keyword"><span class="hljs-keyword">new</span></span> <span class="hljs-keyword"><span class="hljs-keyword">object</span></span> $ob1<span class="hljs-string"><span class="hljs-string">" $a = new-object $ob1 "</span></span>Members <span class="hljs-keyword"><span class="hljs-keyword">of</span></span> the $ob1<span class="hljs-string"><span class="hljs-string">" "</span></span><span class="hljs-keyword"><span class="hljs-keyword">New</span></span> <span class="hljs-keyword"><span class="hljs-keyword">object</span></span> $ob1 created<span class="hljs-string"><span class="hljs-string">" $a | Get-Member } Catch [System.Management.Automation.PSArgumentException] { "</span></span>invalid <span class="hljs-keyword"><span class="hljs-keyword">object</span></span><span class="hljs-string"><span class="hljs-string">" } Catch [system.exception] { "</span></span>caught a <span class="hljs-keyword"><span class="hljs-keyword">system</span></span> <span class="hljs-keyword"><span class="hljs-keyword">exception</span></span><span class="hljs-string"><span class="hljs-string">" } Finally { "</span></span><span class="hljs-keyword"><span class="hljs-keyword">end</span></span> <span class="hljs-keyword"><span class="hljs-keyword">of</span></span> script<span class="hljs-string"><span class="hljs-string">" }</span></span></code> </pre><br>  The following figure shows the output of the <i>TestTryMultipleCatchFinally.ps1</i> script.  Two changes were made: The <b>$ ErrorActionPreference</b> and <b>Get-Content foo</b> commands were <b>commented out</b> .  Thus, the generated error will occur when trying to create a non-existent object.  To find a specific error, I explored the <b>$ error</b> variable after running the <i>TestTryMultipleCatchFinally.ps1</i> script.  The error is indicated in the <b>Exception</b> field. <br><br><pre> <code class="hljs haskell"><span class="hljs-type"><span class="hljs-type">PS</span></span> <span class="hljs-type"><span class="hljs-type">C</span></span>:\&gt; $error | fl * -<span class="hljs-type"><span class="hljs-type">F</span></span> <span class="hljs-type"><span class="hljs-type">PSMessageDetails</span></span> : <span class="hljs-type"><span class="hljs-type">Exception</span></span> : <span class="hljs-type"><span class="hljs-type">System</span></span>.<span class="hljs-type"><span class="hljs-type">Management</span></span>.<span class="hljs-type"><span class="hljs-type">Automation</span></span>.<span class="hljs-type"><span class="hljs-type">PSArgumentException</span></span>: <span class="hljs-type"><span class="hljs-type">Cannot</span></span> find <span class="hljs-class"><span class="hljs-keyword"><span class="hljs-class"><span class="hljs-keyword">type</span></span></span><span class="hljs-class"> [foo]: verify that the assembly containing this </span><span class="hljs-keyword"><span class="hljs-class"><span class="hljs-keyword">type</span></span></span><span class="hljs-class"> is loaded. at </span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">System</span></span></span><span class="hljs-class">.</span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">Management</span></span></span><span class="hljs-class">.</span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">Automation</span></span></span><span class="hljs-class">.</span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">MshCommandRuntime</span></span></span><span class="hljs-class">.</span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">ThrowTerminat</span></span></span><span class="hljs-class"> ingError(</span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">ErrorRecord</span></span></span><span class="hljs-class"> </span><span class="hljs-title"><span class="hljs-class"><span class="hljs-title">errorRecord</span></span></span><span class="hljs-class">) </span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">TargetObject</span></span></span><span class="hljs-class"> : </span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">CategoryInfo</span></span></span><span class="hljs-class"> : </span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">InvalidType</span></span></span><span class="hljs-class">: (:) [</span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">New</span></span></span><span class="hljs-class">-</span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">Object</span></span></span><span class="hljs-class">], </span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">PSArgumentException</span></span></span><span class="hljs-class"> </span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">FullyQualifiedErrorId</span></span></span><span class="hljs-class"> : </span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">TypeNotFound</span></span></span><span class="hljs-class">,</span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">Microsoft</span></span></span><span class="hljs-class">.</span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">PowerShell</span></span></span><span class="hljs-class">.</span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">Commands</span></span></span><span class="hljs-class">.</span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">NewObjectCommand</span></span></span><span class="hljs-class"> </span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">ErrorDetails</span></span></span><span class="hljs-class"> : </span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">InvocationInfo</span></span></span><span class="hljs-class"> : </span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">System</span></span></span><span class="hljs-class">.</span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">Management</span></span></span><span class="hljs-class">.</span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">Automation</span></span></span><span class="hljs-class">.</span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">InvocationInfo</span></span></span><span class="hljs-class"> </span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">ScriptStackTrace</span></span></span><span class="hljs-class"> : at &lt;</span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">ScriptBlock</span></span></span><span class="hljs-class">&gt;, </span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">C</span></span></span><span class="hljs-class">:\</span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">Users</span></span></span><span class="hljs-class">\dyak\</span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">SkyDrive</span></span></span><span class="hljs-class">\</span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">Scripts</span></span></span><span class="hljs-class">\habrahabr\</span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">TestTry</span></span></span><span class="hljs-class"> </span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">MultipleCatchFinally</span></span></span><span class="hljs-class">.ps1: line 10 </span><span class="hljs-type"><span class="hljs-class"><span class="hljs-type">PipelineIterationInfo</span></span></span><span class="hljs-class"> : {}</span></span></code> </pre><br><br><img src="https://habrastorage.org/files/fa8/38a/05a/fa838a05a59a48b79d66d2536ff48460.jpg"><br><br>  If the script has several errors, and the value of the <b>$ ErroActionPreference</b> variable is set to ‚Äústop‚Äù, the first error will cause the script to fail.  If you remove comments from the <b>$ ErrorActionPreference</b> and <b>Get-Content</b> commands, the first error will be caught by the <b>System.Exception Catch</b> block and therefore the exception argument will be skipped.  This is seen in the following image: <br><br><img src="https://habrastorage.org/files/cb7/2a2/176/cb72a217610543dbab261ce543c11e90.jpg"><br><br>  In general, tried to translate <a href="http://blogs.technet.com/b/heyscriptingguy/archive/2010/03/11/hey-scripting-guy-march-11-2010.aspx">an article</a> published in the Ed Wilson block.  I hope it will be useful to someone. </div><p>Source: <a href="https://habr.com/ru/post/248217/">https://habr.com/ru/post/248217/</a></p>
<section class="more-articles-navigation-panel js-more-articles-navigation-panel">
<h4>More articles:</h4>
<nav class="list-of-articles-container js-list-of-articles-container"><ul class="list-of-pages js-list-of-pages">
<li><a href="../248205/index.html">PHDays V: Botnet Detection, NFC Stunts, and ‚ÄúSocial Engineers‚Äù Competitions</a></li>
<li><a href="../248207/index.html">Xargs: a variety of use cases</a></li>
<li><a href="../248211/index.html">Simple acceptance of bank card payments in Windows Universal Apps</a></li>
<li><a href="../248213/index.html">The path from beginner to pro: CMS development on the Kohana 3.3 framework</a></li>
<li><a href="../248215/index.html">7 common mistakes when designing a checkout process</a></li>
<li><a href="../248219/index.html">Home automation with openHAB: lighting and remote control of heaters. Part 1</a></li>
<li><a href="../248225/index.html">Yandex investigation: full disclosure about the virus on Facebook</a></li>
<li><a href="../248227/index.html">Pivotal stops developing Groovy & Grails from March 31</a></li>
<li><a href="../248229/index.html">Binary operations on unordered sets</a></li>
<li><a href="../248231/index.html">The main functions of ETL-systems</a></li>
</ul></nav>
</section><br />
<a href="../../allArticles.html"><strong>All Articles</strong></a>
<script src="../../js/main.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
          try {
              w.yaCounter52496797 = new Ya.Metrika({
                  id:52496797,
                  clickmap:true,
                  trackLinks:true,
                  accurateTrackBounce:true,
                  webvisor:true
              });
          } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = "https://mc.yandex.ru/metrika/watch.js";

      if (w.opera == "[object Opera]") {
          d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/52496797" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

<!-- Google Analytics -->
  <script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-134931760-1', 'auto'); ga('send', 'pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async defer></script>

</section>

  <footer class="page-footer">
    <div class="page-footer-legal-info-container page-footer-element">
      <p>
        Weekly-Geekly | <span class="page-footer-legal-info-year js-page-footer-legal-info-year">2019</span>
      </p>
    </div>
    <div class="page-footer-counters-container page-footer-element">
      <a class="page-footer-counter-clustrmap" href='#'  title='Visit tracker'><img src='https://clustrmaps.com/map_v2.png?cl=698e5a&w=271&t=t&d=6iCFw7uJz0zcOaoxz5k5PcLCJUzv2WG8G5V8M3U6Rc4&co=3a3a3a&ct=ffffff'/></a>
    </div>
  </footer>
</body>

</html>